"""Compile a range's traffic policy into the router's nftables ruleset."""

from __future__ import annotations

import ipaddress

from .spec import RangeSpec

WG_IFACE = "wg0"

# Destinations that never count as "internet": private ranges, link-local, loopback, multicast and reserved
# space. The cluster's own networks (reserved_networks in the config) are added, so a cluster whose LAN uses
# public addresses is protected too.
PRIVATE_V4 = ["0.0.0.0/8", "10.0.0.0/8", "100.64.0.0/10", "127.0.0.0/8", "169.254.0.0/16",
              "172.16.0.0/12", "192.0.0.0/24", "192.168.0.0/16", "198.18.0.0/15", "224.0.0.0/4", "240.0.0.0/4"]


def private_set(reserved=()) -> list[str]:
    """PRIVATE_V4 plus reserved networks it does not already cover, without overlaps (nft interval sets reject
    overlapping elements). Unchanged output when nothing new is added keeps existing policy hashes stable."""
    base = [ipaddress.IPv4Network(n) for n in PRIVATE_V4]
    extra = []
    for r in reserved:
        n = ipaddress.ip_network(r, strict=False)
        if n.version == 4 and not any(n.subnet_of(b) for b in base):
            extra.append(n)
    if not extra:
        return list(PRIVATE_V4)
    return [str(n) for n in ipaddress.collapse_addresses(base + extra)]


def _ports(ports: list) -> str:
    items = ", ".join(str(p) for p in ports)
    return f"{{ {items} }}"


def render(spec: RangeSpec, ifmap: dict[str, str], uplink: str, *, build_egress: bool, spec_id: str,
           reserved=()) -> str:
    """ifmap: segment name -> interface name inside the router; uplink: interface name of the NAT uplink;
    reserved: the cluster's own networks (never reachable from the range)."""
    seg_ifs = [ifmap[s.name] for s in spec.segments]
    lines: list[str] = []
    w = lines.append
    w("#!/usr/sbin/nft -f")
    w(f"# Generated by VALOR for range '{spec.name}' (spec {spec_id}). Do not edit: change the spec and re-apply.")
    w(f"# Mode: {'BUILD (temporary internet egress for every segment)' if build_egress else 'FINAL policy'}")
    w("flush ruleset")
    w("")
    w("table inet valor {")
    w("  set private_v4 {")
    w("    type ipv4_addr")
    w("    flags interval")
    w(f"    elements = {{ {', '.join(private_set(reserved))} }}")
    w("  }")
    w("")
    w("  chain input {")
    w("    type filter hook input priority filter; policy drop;")
    w('    iif "lo" accept')
    w("    ct state established,related accept")
    w("    ct state invalid drop")
    w(f"    iifname {{ {', '.join(f'\"{i}\"' for i in seg_ifs)} }} icmp type echo-request accept comment \"segments may ping their gateway\"")
    wg = spec.access.wireguard if spec.access else None
    if wg:
        w(f'    iifname "{uplink}" udp dport {wg.port} accept comment "WireGuard access (access.wireguard)"')
        w(f'    iifname "{WG_IFACE}" ip saddr {wg.network} icmp type echo-request accept comment "peers may ping the router"')
    w("    # No other services are exposed on the router; it is managed through the QEMU guest agent.")
    w("  }")
    w("")
    w("  chain forward {")
    w("    type filter hook forward priority filter; policy drop;")
    w("    ct state established,related accept")
    w("    ct state invalid drop")
    for r in spec.policy:
        src_seg, dst_seg = spec.segment_of(r.from_), spec.segment_of(r.to)
        src, dst = spec.endpoint_cidr(r.from_), spec.endpoint_cidr(r.to)
        match = f'iifname "{ifmap[src_seg]}" oifname "{ifmap[dst_seg]}" ip saddr {src} ip daddr {dst}'
        label = r.description or f"{r.from_} -> {r.to} {r.proto}{' ' + ','.join(map(str, r.ports)) if r.ports else ''}"
        label = label.replace('"', "'")
        if r.proto in ("tcp", "udp"):
            w(f"    {match} {r.proto} dport {_ports(r.ports)} accept comment \"policy: {label}\"")
        elif r.proto == "icmp":
            w(f"    {match} meta l4proto icmp accept comment \"policy: {label}\"")
        else:
            w(f"    {match} accept comment \"policy: {label}\"")
    if wg:
        for name in wg.reach or [s.name for s in spec.segments]:
            w(f'    iifname "{WG_IFACE}" oifname "{ifmap[name]}" ip saddr {wg.network} ip daddr {spec.segment(name).cidr} '
              f'accept comment "WireGuard peers -> {name}"')
    for s in spec.segments:
        if s.internet or build_egress:
            why = "internet egress" if s.internet else "temporary build egress"
            w(f'    iifname "{ifmap[s.name]}" oifname "{uplink}" ip saddr {s.cidr} ip daddr != @private_v4 '
              f'accept comment "{s.name}: {why} (public addresses only)"')
    w("  }")
    w("")
    w("  chain output {")
    w("    type filter hook output priority filter; policy accept;")
    w("  }")
    w("}")
    w("")
    w("table ip valor_nat {")
    w("  chain postrouting {")
    w("    type nat hook postrouting priority srcnat; policy accept;")
    w(f'    oifname "{uplink}" masquerade')
    w("  }")
    w("}")
    return "\n".join(lines) + "\n"


def router_script(ruleset: str) -> str:
    """Bash run inside the router: validate, install and load the ruleset; enable forwarding."""
    return f"""set -euo pipefail
command -v nft >/dev/null || {{ export DEBIAN_FRONTEND=noninteractive; apt-get -o DPkg::Lock::Timeout=600 -qq -y install nftables >/dev/null; }}
cat > /etc/nftables.conf.valor-new <<'VALOR_NFT_EOF'
{ruleset}VALOR_NFT_EOF
nft -c -f /etc/nftables.conf.valor-new
mv /etc/nftables.conf.valor-new /etc/nftables.conf
chmod 600 /etc/nftables.conf
cat > /etc/sysctl.d/90-valor-router.conf <<'EOF'
# VALOR range router: forward IPv4 between segments (filtered by nftables), no IPv6 forwarding
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 0
net.ipv4.conf.all.rp_filter = 1
EOF
sysctl -q --system >/dev/null
systemctl enable -q nftables
nft -f /etc/nftables.conf
echo ok
"""
