#!/usr/bin/env python3
"""Regenerate appliance/requirements.lock from appliance/requirements.in (developer tool).

The VALOR VM runs Ubuntu 24.04 (CPython 3.12, x86_64). This resolves the full dependency closure for that
platform with `pip download`, then writes every pinned version with the SHA-256 of *all* its published files
(from PyPI's JSON API), so `pip install --require-hashes` accepts whichever wheel pip picks on the target and
nothing else.

    python3 tools/lock.py            # needs pip and internet access
"""

import json
import re
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IN, OUT = ROOT / "appliance" / "requirements.in", ROOT / "appliance" / "requirements.lock"
PLATFORMS = [f"manylinux_2_{n}_x86_64" for n in range(39, 16, -1)] + ["manylinux2014_x86_64", "linux_x86_64"]


def main() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        cmd = [sys.executable, "-m", "pip", "download", "-q", "--only-binary=:all:", "--python-version", "3.12",
               "--implementation", "cp", "--abi", "cp312", "-d", tmp, "-r", str(IN)]
        for p in PLATFORMS:
            cmd += ["--platform", p]
        subprocess.run(cmd, check=True)
        pins = {}
        for f in sorted(Path(tmp).iterdir()):
            name, version = f.name.split("-")[:2]
            pins[re.sub(r"[-_.]+", "-", name).lower()] = version
    lines = ["# Generated by tools/lock.py from requirements.in - do not edit by hand.",
             "# Python packages for the VALOR VM (Ubuntu 24.04, CPython 3.12, x86_64), installed with",
             "#   pip install --require-hashes -r requirements.lock", ""]
    for name, version in sorted(pins.items()):
        with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json", timeout=30) as r:
            files = json.load(r)["urls"]
        hashes = sorted({f["digests"]["sha256"] for f in files})
        lines.append(f"{name}=={version} \\")
        lines += [f"    --hash=sha256:{h}" + (" \\" if i < len(hashes) - 1 else "") for i, h in enumerate(hashes)]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(pins)} packages")


if __name__ == "__main__":
    main()
